# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04\x64\x65mo\"$\n\x01\x41\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\t\n\x01z\x18\x03 \x01(\r\"$\n\x01\x42\x12\t\n\x01u\x18\x01 \x01(\x01\x12\t\n\x01v\x18\x02 \x01(\x01\x12\t\n\x01w\x18\x03 \x01(\x01\"J\n\x05reply\x12\r\n\x05msgId\x18\x01 \x01(\r\x12\x14\n\x01\x61\x18\x02 \x01(\x0b\x32\x07.demo.AH\x00\x12\x14\n\x01\x62\x18\x03 \x01(\x0b\x32\x07.demo.BH\x00\x42\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_A']._serialized_start=20
  _globals['_A']._serialized_end=56
  _globals['_B']._serialized_start=58
  _globals['_B']._serialized_end=94
  _globals['_REPLY']._serialized_start=96
  _globals['_REPLY']._serialized_end=170
# @@protoc_insertion_point(module_scope)
