# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0elight_detector\"<\n\x0e\x44\x61taBusRequest\x12*\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\x18.light_detector.DataType\"m\n\x0f\x44\x61taBusResponse\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\r\x12*\n\x08\x64\x61taType\x18\x02 \x01(\x0e\x32\x18.light_detector.DataType\x12\r\n\x05value\x18\x03 \x01(\r\x12\r\n\x05nonce\x18\x04 \x01(\r*8\n\x08\x44\x61taType\x12\x07\n\x03Raw\x10\x00\x12\x08\n\x04\x46ull\x10\x01\x12\x0c\n\x08Infrared\x10\x02\x12\x0b\n\x07Visible\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=203
  _globals['_DATATYPE']._serialized_end=259
  _globals['_DATABUSREQUEST']._serialized_start=30
  _globals['_DATABUSREQUEST']._serialized_end=90
  _globals['_DATABUSRESPONSE']._serialized_start=92
  _globals['_DATABUSRESPONSE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
